### PR TITLE
Fix Line trie_fnmatch using search string for prefix slice

### LINKED ISSUE #25: HWDB: Trie search not working correctly
Seems like I didn't test fully #23 as it still doesn't seem to work properly. It often incorrectly returns:

## Too many keys

```
❯ cargo run --example systemd-hwdb "usb:v1D6Bp0001"
ID_USB_CLASS_FROM_DATABASE: Audio
ID_USB_SUBCLASS_FROM_DATABASE: Boot Interface Subclass
ID_USB_SUBCLASS_FROM_DATABASE: MCTCP Host
# ^ above are not valid returns
ID_VENDOR_FROM_DATABASE: Linux Foundation
ID_AUTOSUSPEND: 1
ID_MODEL_FROM_DATABASE: 1.1 root hub
```

```
❯ systemd-hwdb query usb:v1D6Bp0001                                                                                                                                                          
ID_VENDOR_FROM_DATABASE=Linux Foundation                                                                                                                                                     
ID_AUTOSUSPEND=1                                                                                                                                                                             
ID_MODEL_FROM_DATABASE=1.1 root hub 
```

# No results

```
❯ cargo run --example systemd-hwdb "usb:v*p*d*dc03*"
```

```
❯ systemd-hwdb query "usb:v*p*d*dc03*"
ID_USB_CLASS_FROM_DATABASE=Human Interface Device
```

This isn't critical for me but wanted to capture the issue. I know hwdb isn't well documented so it's hard to dig into this bug. Since it almost there though wondered if you have any ideas. I have updated the test and the example above is in my fork: https://github.com/cr8t/udev/compare/main...tuna-f1sh:udev:main

### PR DESCRIPTION
**Pull request by tuna-f1sh**
Closes #25. After some digging around [sd-hwdb.c](https://github.com/systemd/systemd/blob/main/src/libsystemd/sd-hwdb/sd-hwdb.c) the culprit for this bug was something silly as always! The `start` and `end` vars, obtained based on the passed start value and null terminator was using the `search` query rather than `prefix`. This values are used to generate the slice added to the `Line` and [should use `prefix`](https://github.com/systemd/systemd/blob/main/src/libsystemd/sd-hwdb/sd-hwdb.c#L186).

What made the results odd, was the fact that the passed `search` in the Rust udev would not even have a null terminator since it's a Rust String; it would always result in the `unwrap_or(search.len())`. So the prefix being searched was a slice based on the passed `p` and length of search. The result was a mostly correct trie line but not always and sometimes with too much/little matching. 

I made some other changes whilst debugging I think make sense for readability and robustness. Also adds the `system-hwdb` example and examples the hwdb parser tests. Outstanding question:

* I had multiple matches of the same key so changed `unique` to default `true`: https://github.com/cr8t/udev/compare/main...tuna-f1sh:udev:main?expand=1#diff-06060802aa63cf0eea53aba4bb5b2c88a0b96d2dc21bbe7a7736d21e31b127b5R31 . I'm not sure if this is your intent or not? Can also check in the `add_property` function if the key exists. [systemd actually has some logic for priority of multiple matches](https://github.com/systemd/systemd/blob/main/src/libsystemd/sd-hwdb/sd-hwdb.c#L133) which would take a lot of changes to implement.

### CODE REVIEW

File: src/hwdb/trie.rs [hunk 1]
```diff
@@ -25,8 +25,8 @@ pub fn trie_string(hwdb_buf: &[u8], offset: usize) -> &str {
             .map(|end| offset + end)
             .unwrap_or(buf_len);
 
-        std::str::from_utf8(&hwdb_buf[offset..str_end]).unwrap_or("")
+        std::str::from_utf8(&hwdb_buf[offset..str_end]).expect("invalid UTF-8 string")
```
Comment (cr8t) [inline src/hwdb/trie.rs:28]: If we're going to error on failing to create a `&str` we should change the return to a `Result` type, and bubble-up the error. I would prefer to remove as many `panic`s as possible.

File: src/hwdb/line.rs [hunk 2]
```diff
@@ -81,29 +79,26 @@ impl LineBuf {
...
+                .iter()
+                .skip(p)
+                .position(|c| *c == b'\0')
+                .unwrap_or(prefix_len),
+        );
 
-        if start <= prefix_len && end <= prefix_len && start <= end {
+        // the logic of add only if within bounds but always remove is odd but the linebuf_add return is not checked in https://github.com/cr8t/udev/issues/25#L187
+        // so behavior should match
+        if start < prefix_len && end <= prefix_len {
```
Comment (cr8t) [inline src/hwdb/line.rs:94]:
```suggestion
        if (start..=end).contains(&prefix_len) {
```
minor lint nit

**Review by cr8t — CHANGES_REQUESTED** [review]
Thank you for the fixes! LGTM for the most part, with some minor changes requested.

File: src/hwdb/trie.rs (hunk 1 above)
Comment (tuna-f1sh) [reply src/hwdb/trie.rs]: Yes you're right. I've done the work to change this to a `Result` return instead of "". From my understanding this conditions are not normal and it should propagate rather than silently return "".

**Review by cr8t — APPROVED** [review]
